version: "3.8"
services:
  frontend:
    image: teamodoro-frontend
    build: ./frontend
    volumes:
      - ./frontend:/home/app/teamodoro
      - node_modules:/home/app/teamodoro/node_modules
    ports:
      - 4200:4200
  backend:
    image: teamodoro-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 81:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
volumes:
  node_modules:
